sources:
  - name: dunder_mifflin
    database: raw
    schema: dunder_mifflin
    tables:
      - name: categories
      - name: customers
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: shippers
      - name: suppliers